---
- block:
    - set_fact:
        patch_only_namespace:
          first: patch-only-1
          second: patch-only-2

    - name: assert that parameters are mutually exclusive
      kubernetes.core.k8s:
        apply: yes
        patch_only: yes
        definition:
          apiVersion: v1
          kind: Namespace
          metadata:
            name: "{{ patch_only_namespace.first }}"
      register: mutually_exclusive
      ignore_errors: yes

    - name: assert mutually exclusive
      assert:
        that:
          - mutually_exclusive is failed
          - '"parameters are mutually exclusive" in mutually_exclusive.msg'

    - name: Ensure namespace {{ patch_only_namespace.first }} exist
      kubernetes.core.k8s:
        definition:
          apiVersion: v1
          kind: Namespace
          metadata:
            name: "{{ patch_only_namespace.first }}"
        wait: yes

    - name: Ensure namespace {{ patch_only_namespace.second }} does not exist
      kubernetes.core.k8s_info:
        kind: namespace
        name: "{{ patch_only_namespace.second }}"
      register: second_namespace

    - name: assert that second namespace does not exist
      assert:
        that:
          - second_namespace.resources | length == 0

    - name: patch only existing resources
      kubernetes.core.k8s:
        patch_only: yes
        wait: yes
        definition: |
          ---
          apiVersion: v1
          kind: Namespace
          metadata:
            name: "{{ patch_only_namespace.first }}"
            labels:
              patch: ansible
          ---
          apiVersion: v1
          kind: Namespace
          metadata:
            name: "{{ patch_only_namespace.second }}"
            labels:
              patch: ansible
      register: patch_resource

    - name: assert that patch succeed
      assert:
        that:
          - patch_resource.changed
          - patch_resource.result.results | selectattr('warning', 'defined') | list | length == 1

    - name: Ensure namespace {{ patch_only_namespace.second }} was not created
      kubernetes.core.k8s_info:
        kind: namespace
        name: "{{ patch_only_namespace.second }}"
      register: second_namespace

    - name: assert that second namespace does not exist
      assert:
        that:
          - second_namespace.resources | length == 0

    - name: patch all resources (create if does not exist)
      kubernetes.core.k8s:
        definition: |
          ---
          apiVersion: v1
          kind: Namespace
          metadata:
            name: "{{ patch_only_namespace.first }}"
            labels:
              patch: ansible
          ---
          apiVersion: v1
          kind: Namespace
          metadata:
            name: "{{ patch_only_namespace.second }}"
            labels:
              patch: ansible
        wait: yes
      register: patch_resource

    - name: Ensure namespace {{ patch_only_namespace.second }} was created
      kubernetes.core.k8s_info:
        kind: namespace
        name: "{{ patch_only_namespace.second }}"
      register: second_namespace

    - name: assert that second namespace exist
      assert:
        that:
          - second_namespace.resources | length == 1

  always:
    - name: Remove namespace
      kubernetes.core.k8s:
        kind: Namespace
        name: "{{ item }}"
        state: absent
      with_items:
        - "{{ patch_only_namespace.first }}"
        - "{{ patch_only_namespace.second }}"
      ignore_errors: true
