---
driver:
  name: delegated
  options:
    managed: false
    login_cmd_template: 'docker exec -ti {instance} bash'
    ansible_connection_options:
      ansible_connection: docker
lint: |
  set -e
  yamllint .
  flake8
platforms:
  - name: instance-kind
    image: sameersbn/squid:3.5.27-2
    exposed_ports:
      - 3128/tcp
    published_ports:
      - 0.0.0.0:3128:3128/tcp
    volumes:
      - squid.passwd:/etc/squid/passwd
      - squid.conf:/etc/squid/squid.conf
    privileged: true

provisioner:
  name: ansible
  log: true
  config_options:
    inventory:
      enable_plugins: kubernetes.core.k8s
  lint: {}
  inventory:
    hosts:
      plugin: kubernetes.core.k8s
    host_vars:
      localhost:
        ansible_python_interpreter: '{{ ansible_playbook_python }}'
  env:
    ANSIBLE_FORCE_COLOR: 'true'
  options:
    vvv: True
scenario:
  name: default
  test_sequence:
    - lint
    - syntax
    - converge
    - verify
