---
- name: Prepare
  hosts: localhost
  connection: local
  gather_facts: no

  collections:
    - kubernetes.core

  tasks:
    - name: Include drain.yml
      include_tasks:
        file: tasks/drain.yml
