---
- name: Converge
  hosts: localhost
  connection: local

  collections:
    - kubernetes.core

  tasks:
    - name: Verify cluster is working.
      k8s_info:
        namespace: kube-system
        kind: Pod
      register: pod_list

    - name: Verify cluster has more than 5 pods running.
      assert:
        that: (pod_list.resources | count) > 5

    - name: Include drain.yml
      include_tasks:
        file: tasks/drain.yml
        apply:
          tags: [ drain, k8s ]
      tags:
        - always
