name: ansible bot
on:
  issues:
    types:
      - opened
      - reopened
      - edited
  pull_request_review:
    types:
      - submitted
      - edited
      - dismissed
  pull_request:
    types:
      - opened
      - edited
      - reopened
      - synchronize

jobs:
  labels:
    uses: abikouo/gha_testing/.github/workflows/ansible_bot.yml@main
