name: tests
concurrency:
  group: docs-${{ github.head_ref }}
  cancel-in-progress: true
on:
  pull_request:
    types:
      - opened
      - reopened
      - labeled
      - unlabeled
      - synchronize
    branches:
      - main
      - stable-*
    tags:
      - '*'

jobs:
  build-ansible-collection:
    name: Build ansible collection
    env:
      source_directory: "./source"
      cloudcommon_directory: "./cloudcommon"
    runs-on: ubuntu-latest
    steps:
      - name: checkout repository
        uses: actions/checkout@v3
        with:
          path: ${{ env.source_directory }}
          fetch-depth: "0"

      - name: checkout ansible-collections/cloud.common
        uses: abikouo/github_actions/.github/actions/checkout_repository@clone_with_dependencies
        with:
          repository: ansible-collections/cloud.common
          destination_directory: ${{ env.cloudcommon_directory }}
          ref: main