name: ci tests
concurrency:
  group: docs-${{ github.head_ref }}
  cancel-in-progress: true
on:
  pull_request:
    types:
      - opened
      - reopened
      - labeled
      - unlabeled
      - synchronize
    branches:
      - main
      - stable-*
    tags:
      - '*'

jobs:
  resolve_dep:
    name: Resolve dependencies
    env:
      source_directory: "./source"
    runs-on: ubuntu-latest
    steps:
      - name: checkout another pull request merge
        uses: abikouo/github_actions/.github/actions/checkout_repositories@clone_with_dependencies
        with:
          repository: ansible/ansible-zuul-jobs
          destination_directory: ${{ env.source_directory }}
          pull_request_body: ${{ github.event.pull_request.body }}