name: Integration
concurrency:
  group: ${{ github.head_ref }}
  cancel-in-progress: true

on:
  pull_request:
    types:
      - opened
      - reopened
      - labeled
      - unlabeled
      - synchronize
    branches:
      - main
      - stable-*
    tags:
      - '*'

jobs:
  auto_changelog:
    name: add changelog to pull request if required
    runs-on: ubuntu-latest
    steps:
      - name: Checkout the collection repository
        uses: actions/checkout@v3

      - name: Set up Python '3.9'
        uses: actions/setup-python@v4
        with:
          python-version: '3.9'

      - name: Install python dependencies
        run: |
          pip install -U pyyaml
        shell: bash

      - name: Download script
        run: >-
          curl -o /tmp/add_changelog.py
          https://github.com/abikouo/gha_testing/blob/main/tools/add_changelog.py

      - name: Validate or add pull request changelog
        run:
          python3 /tmp/add_changelog.py
        env:
          PR_BASE_REF: ${{ github.event.pull_request.base.ref }}
        if: "!contains(github.event.pull_request.labels.*.name, 'skip-changelog')"
